# Generated by Django 3.1.4 on 2021-01-07 09:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ManyToManyField(to='frontend.Category'),
        ),
    ]
